### ISSUE TITLE
How to use with Ubuntu and Chromium 

### ISSUE THREAD

**Issue by bsurai** [krisselden/chrome-debugging-client#16]
There is an example with 'canary':  
`const process = await session.spawn("canary", {
    additionalArguments: ['--headless'],
    windowSize: { width: 640, height: 320 }
  });`

But on my device only Chrome and Chromium are installed. How should this example look with Chrome and Chromium browsers, when Ubuntu installed on my device?

How about to change type of spawn's first parameter? We can use `type BrowserType = 'canary' | 'chrome' | 'chromium'` instead of pure `string` type. Then we'll be able to use IntelliSense to fill browser type parameter.

**Comment by krisselden** [comment]
```sh
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update 
sudo apt-get install google-chrome-beta
```

```ts
const process = await session.spawn('exact', {
  executablePath: '/usr/bin/google-chrome-beta',
  additionalArguments: ['--headless',
                        '--disable-gpu',
                        '--hide-scrollbars',
                        '--mute-audio'],
  windowSize: { width: 640, height: 320 },
});
```
