### ISSUE TITLE
Allow spawning browser at custom window sizes.

### ISSUE THREAD

**Issue by rwjblue** [krisselden/chrome-debugging-client#2]
This is currently hard coded to 414x736 which seems fine for emulating mobile dimensions, but it should be possible to spawn at other sizes.

Currently hard coded at:
- https://github.com/krisselden/chrome-debugging-client/blob/master/lib/browser-spawner.ts#L81
- https://github.com/krisselden/chrome-debugging-client/blob/master/lib/browser-spawner.ts#L71

---

I'm happy to work on this, but I am not sure what the desired API would be for passing this through (from chrome-tracing).  It seems reasonable to me for this to be part of the `browser` options [passed from here](https://github.com/krisselden/chrome-tracing/blob/master/lib/benchmark.ts#L83) and ultimately [calling here](https://github.com/krisselden/chrome-debugging-client/blob/master/lib/session.ts#L91), but the name of that options hash is `ResolveOptions` so I wasn't sure if it was explicitly for resolving the browser to be used or if we can expand it to be general purpose `SpawnOptions` or somesuch.

**Comment by krisselden** [comment]
better late than never.
