### ISSUE TITLE
Resuming node execution

### ISSUE THREAD

**Issue by tostercx** [krisselden/chrome-debugging-client#5]
Hey,

I'm trying to attach to a node process started with `--inspect-brk`. AFAIK that should launch the process and break on the first line pausing the debugger. So I assume I'd need to run `Debugger.resume()` however it never seems to return and just hangs.

The connection is ok, "tabs" list fine. Can anyone tell me what I'm doing wrong?

    import { createSession } from "chrome-debugging-client";
    import { Debugger } from "chrome-debugging-client/dist/protocol/v8";

    createSession(async (session) => {
      
      // spawn node
      const child_process = require('child_process');
      child_process.exec('node --inspect-brk test.js');
      
      // open the REST API for tabs
      const client = session.createAPIClient("127.0.0.1", 9229);
      
      // get the active "tab"
      const tabs = await client.listTabs();
      const tab = tabs[0];
      await client.activateTab(tab.id);

      // open the debugger protocol
      // https://chromedevtools.github.io/devtools-protocol/
      const debuggerClient = await session.openDebuggingProtocol(tab.webSocketDebuggerUrl);
      
      // get debugger interface
      const dbg = new Debugger(debuggerClient);
      
      
      console.log('aaa');
      //await dbg.enable();
      //console.log('bbb'); // <-- never happens?
      await dbg.resume();
      console.log('ccc'); // <-- never happens?
      
      
      return 'the end';
    }).then((data) => {
      console.dir(data);
    }).catch((err) => {
      console.error(err);
    });

**Comment by krisselden** [comment]
don't you need the --inspect arg as well?

**Comment by krisselden** [comment]
Also, should use spawn, you don't use the rest API, node prints the web socket URL

**Comment by krisselden** [comment]
Prints it to stderr

**Comment by krisselden** [comment]
also, I think you want this https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#method-runIfWaitingForDebugger

**Comment by krisselden** [comment]
Here is an example https://gist.github.com/krisselden/16f0a81d77cdc34a8da723bbd22bfbd6

**Comment by tostercx** [comment]
Thank you!!! <3

**Comment by krisselden** [comment]
it is unfortunate that the ephemeral port support was only recently added https://github.com/nodejs/node/commit/399cb25f6266a17f0e5ed838b37b9c8299a87224

**Comment by krisselden** [comment]
I'm tempted to add a spawnNode method, but I kind of wish it supported ephemeral ports.

**Comment by tostercx** [comment]
A node spawner would be nice. Could just set the port manually/use the default until that gets to stable?

**Comment by tostercx** [comment]
Hey, I have another noob question...
Say I set a breakpoint somewhere, catch the ```paused``` event and then let everything run - how do I keep the session open?

    createSession(async (session) => {
      
      // ...
    
      dbg.paused = x => {
        console.log('pause');
      }
      
      await dbg.setBreakpointByUrl({
        lineNumber: 1,
        url: tab.url,
      });
      
      // dummy await op to keep the session alive
      while(1) await dbg.setBreakpointsActive({active: true});
    })

If I let createSession end, I don't get the callbacks. I assume the connection is dropped. Am I missing something obvious?

**Comment by tostercx** [comment]
A dummy sleep function does a better job, tho I still can't seem to find an event that fires when the process is done with the js. The process doesn't exit either, so I can't use that to trigger ending the session.

    var done = false;
    
    function sleep() {
      return new Promise(resolve => setTimeout(resolve, 100));
    }
    
    while(!done) await sleep();

**Comment by krisselden** [comment]
@tostercx node waits for the debugger to detach (close the websocket). It writes a message to stderr that it is waiting for the debugger to detach.

`Waiting for the debugger to disconnect...`

You'll need to make another promise for that if you want to disconnect, but generally debuggers wait for the developer to disconnect.  I'm curious what you are building. Is this some kind of automated debugging?

To wait for the pause event, you need to create a new Promise and resolve it on the pause event, and await the promise after resuming.

**Comment by tostercx** [comment]
Didn't notice that on stderr, thanks!

I'm reversing a well obfuscated script and need to dump some values automatically each time it regenerates. Attaching to the debugger seems like an easier route than automatically modifying it.

**Comment by krisselden** [comment]
@tostercx it only outputs `Waiting for the debugger to disconnect...` if it reaches where it normally would exit, the idea is you may still want to inspect stuff with the runtime before it exits
